apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    name: django-configmap
data:
  SECRET_KEY: "REPLACE_ME_IM_A_SECRET_KEY"
  DATABASE_URL: postgres://user:passwordfordb@host:port/dbname
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
